---
pagetitle: "Practical information"
---

[Montreal Tourism office](https://www.mtl.org/en/what-to-do/business-events) has practical information about the city.

## Travel and visa

You may need an [electronic travel authorization (eTA)](https://www.canada.ca/en/immigration-refugees-citizenship/services/visit-canada/eta.html) or a visitor visa. Check this [video](https://youtu.be/aYz9de2Qd_U?list=TLGGbdshJm7bkEQwODA3MjAyNQ) for more details about the application. Please contact the organizing committee if you need a letter for your visa application.

[Montréal-Trudeau International Airport (YUL)](https://www.admtl.com/en-CA/) is well connected with major American and European cities. The airport is easily reached via the [747 bus](https://www.stm.info/en/info/networks/bus-network-and-schedules-enlightened/747-yul-montreal-trudeau-airport-downtown).

## Accommodation

Please note that [Montreal International Jazz Festival](https://montrealjazzfest.com/) runs from June 25th until July 4th. We encourage you to secure your accommodation well in advance, particularly if you plan to attend the short courses over the weekend.

The organizing committee will contact hotels to book rooms at a discounted rate. There are  [numerous hostels, hotels and bed and breakfasts close to downtown](https://www.mtl.org/en/Accommodations?prod_en_random%5BrefinementList%5D%5B_filter_product_neighbourhoods%5D%5B0%5D=Downtown&prod_en_random%5BrefinementList%5D%5B_filter_product_neighbourhoods%5D%5B1%5D=Les%20Quartiers%20du%20Canal&prod_en_random%5BrefinementList%5D%5B_filter_product_neighbourhoods%5D%5B2%5D=Mount%20Royal%2C%20Outremont%20and%20Westmount&prod_en_random%5BrefinementList%5D%5B_filter_product_neighbourhoods%5D%5B3%5D=Old%20Montr%C3%A9al%20and%20Old%20Port).

