---
title: "Venue"
---

The conference and satellite courses will take place in the [Hélène-Desmarais building] in downtown Montréal.
Consult the website for a map of the floors ([3rd floor](https://www.hec.ca/en/campus/helene-desmarais-building/plan-level-3) and [4th floor](https://www.hec.ca/en/campus/helene-desmarais-building/plan-level-4))

The address of the venue is 501, rue de la Gauchetière Ouest, Montréal, H2Z 1Z5.

```{r}
#| eval: true
#| echo: false
#| out-width: '90%'
library(leaflet)
leaflet() |>
  addTiles() |>  # Add default OpenStreetMap map tiles
  addMarkers(lng=-73.5644991,
             lat=45.5027154,
             popup="HEC Montréal - Hélène-Desmarais building")
```


The downtown campus is easily reached by public transport, either via [metro](https://www.stm.info/en/info/networks/metro) ([Square-Victoria-OACI station](https://www.stm.info/fr/infos/reseaux/metro/square-victoria-oaci), orange line), or from the [Gare Centrale REM station](https://rem.info/en/travelling/stations/gare-centrale).


The coffee breaks and standing lunches will take place in the A.373 Centre de conférence Claude-Séguin, located next to the *Entrée Famille Karim (boul. René-Lévesque Ouest).*

Plenary talks will take place in room A.335 Amphithéâtre Rachelle et Alain-Paris.

Registration will be at room A.393.

Contributed and invited talks will be in classrooms

- C.403 Louis-R.-Chênevert
- C.409 Gilles-Labbé
- C.415 Pierre Fitzgibbon
- C.406 Josée-Fiset
- C.412 Malette

<!--
Please bring a copy of your presentation on a USB stick at least 15 minutes before the scheduled start of your session.

-->




